### PR TITLE
initial integration of the v3 api

### PR DESCRIPTION
**Pull request by rybit**
This does all the `/list` endpoints. I wanted to get the initial structure for all of the following endpoints and get your feedback early. 

I tried to keep in with your style, feedback is super welcome.

### CODE REVIEW

**Comment by zeekay** [comment]
At the minimum List and Member APIs are working for me. Needs extensive testing still.

**Comment by mattbaird** [comment]
Maybe we should think about using branches and tagging to support multiple versions of the API, unless we wanted to build infrastructure for delegating to the appropriate version of the calls, although I think that could get messy. Thoughts?

**Comment by zeekay** [comment]
Since there is little in common between 2.0 and 3.0 I would not delegate calls. I think importing a v3 package would be ideal:

```
import "github.com/mattbaird/gochimp/v3"
```

I would not recommend trying to create a unified interface between the two versions of the API.

**Comment by zeekay** [comment]
There might be a few types / utilities you could share between the various APIs, but it probably won't be clear the best approach to take in that regard until you've lived with 3.0 for a while.

**Comment by mattbaird** [comment]
I agree with not sharing, what about using branches, is that best practice?

**Comment by zeekay** [comment]
I don't think it's idiomatic in this particular case. In general, I don't think that's a good idea for a couple of reasons:
- Breaks `go get`
- More work to keep in sync with master
- Non-intuitive

**Comment by mattbaird** [comment]
If we did the branching approach, I would use http://labix.org/gopkg.in

regardless, we still need tests for the new stuff.

finally - thank you for your hard work!

**Comment by rybit** [comment]
hmmm that gopkg is an interesting idea, but I think that if we just package this off we will make it easier. more idiomatic. 

I will try to get some tests around the actual api calls tonight. It should be simple. That is the only real part I am going to test (it is the non-boilerplate part).

**Comment by mattbaird** [comment]
Because this is net new, and the code looks reasonable, I don't have a problem merging it now and then continuing to improve it. your thoughts?

**Comment by hwsoderlund** [comment]
Any updates on when this might be merged? We are just now starting to use the mailchimp parts of the api. Mandrill is all we have used it for so far. Our first step will be small, just adding members to mailing lists, but we have decided to use the v3 api, and it would be really nice if we could keep using gochimp.

**Comment by rybit** [comment]
I am happy to see it merged. I won't have much time to expand on it, but it
is a good base.

**Comment by zeekay** [comment]
I'd prefer to pull it out into it's own project for two reasons:

1. So that it can be licensed MIT.
2. There is no overlap with existing project and I don't think anyone desires interoperability between the original package and the new 3.0 work.

As it doesn't utilize any of the existing gochimp code, I created a new repo which I will be maintaining and extending as my company extends our Mailchimp integration's support: https://github.com/zeekay/gochimp3. It has the initial code committed by Ryan plus everything I have been working on since.

**Comment by mattbaird** [comment]
I respect your decision, however splintering mailchimp support feels wrong.

**Comment by dolmen** [comment]
Please add a pointer to that fork in the README.

**Pull request closed without merging**
